### ISSUE TITLE
Reading .nc files with Paraview

### ISSUE THREAD

**Issue by Yangtze20** [Exawind/amr-wind#1674]
Hello developers,
I'm a Master in Mechanics but I don't know much about AMR-Wind file format, I tried to use Paraview to read abl_statistics_14400.nc file directly from /precursor/postprocessing folder but it failed, here's the file for my environment：

```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - amr-wind@main+netcdf+openfast
  - openfast@3.5.3+rosco
  - py-matplotlib
  - qt@5
  - paraview+opengl2+qt
  view: false
  concretizer:
    unify: true
  include:
  - include.yaml
  develop:
    amr-wind:
      spec: amr-wind@=main
    openfast:
      spec: openfast@=3.5.3
  packages:
    gcc:
      externals:
      - spec: gcc@4.8.5 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran

```
The programme reports the error as follows：

![Image](https://github.com/user-attachments/assets/57c4159d-c01d-4ca6-b070-4739d5e1a092)
Sincere thanks and best regards!
